services:
  stan:
    command:
      - "--cluster_id"
      - wbl0ns
      - "--user"
      - wbl0user
      - "--pass"
      - wbl0pass
    image: nats-streaming:latest
    restart: always
    container_name: nats-streaming
    ports:
      - 4222:4222